Repository BUT2-Alternant/HotHotHot, pull requests merged in 2023-06, with the labels that each got.

#5 feat/fetch
  .gitignore
  Model/FetchModel.js
  constants/UrlConstants.js
Labels: enhancement

#8 feat(history_service): add new history service
  Service/HistoryService.js
Labels: enhancement

#9 feat(history_model): add history model
  Model/HistoryModel.js
Labels: feat

#16 fix(develop_pwa): delete useless file and solve error with url of pwa
  Views/assets/images/manifest/screenshot.webp
  manifest.json
  service/DataService.js
  sw.js
Labels: bug

#18 feat(realtime_service): throw error in fetch if not an entity, and ch…
  Model/FetchModel.js
  Service/RealtimeService.js
Labels: enhancement

#20 feat/controller: added multiple controller
  Controller/HistoryController.js
  Controller/RealTimeController.js
Labels: enhancement

#21 feat(history_cache): add history_cache
  Entity/TemperatureEntity.js
  Model/HistoryModel.js
  Views/assets/script/pwaInstall.js
  Views/html/homepage.html
  sw.js
Labels: enhancement
